Repository chingu-voyages/v41-bears-team-31, pull requests merged in 2022-10, with the labels that each got.

#17 Dev
  README.md
Labels: documentation

#26 updated readme with git and commit instructions
  README.md
Labels: documentation

#27 style change of header file
  components/Layout/Header/Header.tsx
Labels: task

#28 Feature/bears 21 common components
  components/Common/Search/index.tsx
Labels: task

#30 foter added with version and style
  components/Layout/Footer/Footer.tsx
  components/Layout/Footer/index.ts
  components/Layout/PageLayout/PageLayout.tsx
Labels: task

#29 added 2 buttons and changed the font of the app to Roboto
  components/Common/Button/index.tsx
  components/Common/ButtonPrimary/index.tsx
  components/Common/SmallButton/index.tsx
  components/HomePage/HomePage.tsx
  styles/base/typography.css
Labels: task

#31 Feature/bears 21 common components
  components/Common/Button/index.tsx
  components/Common/Card/index.tsx
  components/Common/index.ts
  next.config.js
  public/images/icons/candy.svg
  public/images/icons/pumpkin.svg
Labels: task

#33 some refactoring and reuseable modal with react-portal
  components/Common/Modal/index.tsx
  components/Common/index.ts
  next.config.js
  package.json
  pages/_app.tsx
  pages/_document.tsx
  styles/components/modal.css
  styles/global.css
  tsconfig.json
Labels: enhancement

#34 common layout for everypage except home page, refactored common button
  components/Common/Button/index.tsx
  components/Layout/Footer/Footer.tsx
  components/Layout/Header/Header.tsx
  pages/profile/index.tsx
  public/spookyImg.jpeg
  styles/components/header.css
  styles/global.css
  tailwind.config.js
Labels: enhancement
